server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-gateway-zuul

zuul:
  routes:     # 路由
    order-serviceId:  # zuul的唯一标识，可以任意设置名称，但必须唯一，如果该值与service-id的名称相同时，service-id的值可忽略
      path: /order-zuul/**   # 需要映射的路径
      service-id: microservice-eureka-server  # Eureka中的serviceId
