server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
    instance-id: http://${spring.cloud.client.ipAddress}:${server.port}/
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-eureka-user-hystrix