  server:
  port: 8080
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少发${limit.minMoney}元,最多发${limit.maxMoney}元

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luckymoney?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true  # 显示出SQL语句，方便调试
    hibernate:
      ddl-auto: update  # create 新建
