server:
  port: 7900  # 指定该Eureka实例的端口号
eureka:
  instance:
    prefer-id-address: true    # 是否显示主机的IP
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/      # 指定Eureka服务端地址，相当于找中介(指定注册中心)
spring:
  application:
    name: microservice-eureka-order1  # 指定应用名称
